# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

APP_NAME = "Hobbyloop"
SCHEME = "Hobbyloop"
WEBHOOK_URL = "https://discord.com/api/webhooks/1113104187350327336/u7TEPQ_ilgwnCwb3oy77IEmiuhgllqt_JDYJNNROrVZbJVGsRU_WqHyG7bxkABroxULB"
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

	# app_store_connect_api_key(is_key_content_base64: true, in_house: false)


    build_app(
      workspace: "#{APP_NAME}.xcworkspace",
      scheme: "#{SCHEME}",
      export_method: "app-store"
    )

	increment_build_number({ build_number: latest_testflight_build_number() + 1 })

    upload_to_testflight(skip_waiting_for_build_processing: true)

	discord_notifier(
      webhook_url: "#{WEBHOOK_URL}",
      title: "🚀 #{APP_NAME} iOS 배포 성공",
      description: "#{APP_NAME} iOS를 앱스토어에 성공적으로 배포하였습니다 !"
    )
  end
end
